apiVersion: batch/v1
kind: Job
metadata:
  name: vod-provision
spec:
  template:
    metadata:
      labels:
        app: vod-provision
    spec:
      containers:
        - name: vod-provision
          image: snpsuen/vod-provision:v02
          command: ["/workspace/vod_provision.sh"]
          volumeMounts:
            - name: hls-vol
              mountPath: /var/www/html/hls
            - name: new-vod-vol
              mountPath: /vod/new
      volumes:
        - name: hls-vol
          persistentVolumeClaim:
            claimName: hls-pvc
        - name: new-vod-vol
          hostPath:
            path: /root/vod/new
            type: Directory
      restartPolicy: Never
